{% set setup_py = load_setup_py_data() %}
package:
  name: hydrobr
  version: {{ setup.py.get('version') }}

source:
  path: ./

build:
  scrpit: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  run:
    - python>=3.6
    - pandas>=0.25,<0.26
    - tqdm>=4.31,<4.32
    - requests>=2.21,<2.22
    - matplotlib>=3.1,<3.2
    - plotly>=4.6.0,<4.7
  build:
    - python
    - setuptools

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}